# Numpy
## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [1]:
import numpy as np

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. 

In [2]:
a=np.array([[1, 2], [3, 3], [1, 6], [8, 11], [10, 7]])

In [3]:
print(a)

[[ 1  2]
 [ 3  3]
 [ 1  6]
 [ 8 11]
 [10  7]]


In [4]:
a.ndim

2

In [5]:
a.shape

(5, 2)

Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [6]:
mean_a=a.mean(axis=0)
print(mean_a)

[4.6 5.8]


## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [7]:
a_centered=a-mean_a
print(a_centered)

[[-3.6 -3.8]
 [-1.6 -2.8]
 [-3.6  0.2]
 [ 3.4  5.2]
 [ 5.4  1.2]]


## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [8]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1])

In [9]:
a_centered_sp/(a_centered.shape[0]-1)

10.4

## Задание 4
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [10]:
a_t=np.transpose(a)

In [11]:
np.cov(a_t)

array([[17.3, 10.4],
       [10.4, 12.7]])

# Тема “Работа с данными в Pandas”

## Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [12]:
import pandas as pd

In [13]:
authors={"author_id":[1, 2, 3],
        "author_name":['Тургенев', 'Чехов', 'Островский']}
authors_df=pd.DataFrame(authors)
authors_df

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [14]:
book={"author_id":[1, 1, 1, 2, 2, 3, 3],
      "book_title":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
      "price":[450, 300, 350, 500, 450, 370, 290]    
    }
book_df=pd.DataFrame(book)
book_df

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [15]:
authors_price=pd.merge(authors_df,book_df, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.


In [16]:
authors_price.sort_values(by=['price']).head(5)

author_id author_name            book_title  price
6          3  Островский  Таланты и поклонники    290
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
5          3  Островский                 Гроза    370
0          1    Тургенев           Отцы и дети    450

## Задание 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [17]:
authors_stat=pd.pivot_table(authors_price, values=['price'], index=['author_name'], aggfunc={'price': [min, max, np.mean]})
authors_stat

price                   
               max        mean    min
author_name                          
Островский   370.0  330.000000  290.0
Тургенев     450.0  366.666667  300.0
Чехов        500.0  475.000000  450.0

## Задание 5**
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [19]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [20]:
import numpy as np
pd.pivot_table(authors_price, values=['price'], index=['author_name'], aggfunc={'cover': [np.sum]})

KeyError: "Column 'cover' does not exist!"