# Numpy
## Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [36]:
import numpy as np

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. 

In [37]:
a=np.array([[1, 2], [3, 3], [1, 6], [8, 11], [10, 7]])

In [38]:
print(a)

[[ 1  2]
 [ 3  3]
 [ 1  6]
 [ 8 11]
 [10  7]]


In [39]:
a.ndim

2

In [40]:
a.shape

(5, 2)

Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [41]:
mean_a=a.mean(axis=0)
print(mean_a)

[4.6 5.8]


## Задание 2

Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [42]:
a_centered=a-mean_a
print(a_centered)

[[-3.6 -3.8]
 [-1.6 -2.8]
 [-3.6  0.2]
 [ 3.4  5.2]
 [ 5.4  1.2]]


## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [43]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1])

In [51]:
a_centered_sp/(a_centered.shape[0]-1)

10.4

## Задание 4
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [31]:
a_t=np.transpose(a)

In [35]:
np.cov(a_t)

array([[17.3, 10.4],
       [10.4, 12.7]])

# Тема “Работа с данными в Pandas”

## Задание 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [1]:
import pandas as pd

In [9]:
authors={"ind":[1, 2, 3],
        "auth":['Тургенев', 'Чехов', 'Островский']}
authors_df=pd.DataFrame(authors)
authors_df

ind        auth
0    1    Тургенев
1    2       Чехов
2    3  Островский

Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [13]:
book={"author_id":[1, 1, 1, 2, 2, 3, 3],
      "book_title":['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
      "price":[450, 300, 350, 500, 450, 370, 290]    
    }
book_df=pd.DataFrame(book)
book_df

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290